### ISSUE TITLE
Refactoring version 2

### ISSUE THREAD

**Issue by TatyanaBerlenko** [OSLL/report_generator#19]
Убедиться, что все недочеты из #6 и #10 исправлены и комментарии пофикшены

**Comment by TatyanaBerlenko** [comment]
+ удалить папку venv 
и написать инструкцию активации виртуального окружения

**Comment by light5551** [comment]
https://github.com/OSLL/report_generator/wiki/%D0%90%D0%BA%D1%82%D0%B8%D0%B2%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2%D0%B8%D1%80%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BE%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F
