### ISSUE TITLE
Generation report should be available via ssh

### ISSUE THREAD

**Issue by krinkin** [OSLL/report_generator#2]
Судя по коду сейчас предполагается, что пользователь должен писать имя и пароль и испольовать https ссылку на репозитарий. 

Надо использовать ссылку ssh, вида git@github.com:light5551/generation_report.git

**Comment by light5551** [comment]
Исправлено, теперь пользователь не должен вводить свои данные. 
Полностью избавиться от https ссылок в вводе не получится, потому что при копировании wiki репозитория github дает лишь https, хотя в реализации она модифицируется под ssh.
